### ISSUE TITLE
AppImage shows developer console

### ISSUE THREAD

**Issue by probonopd** [undefinerds/libris#1]
The AppImage shows only the developer console as seen here on Ubuntu MATE 16.04:

![screenshot at 2017-02-19 09 19 00](https://cloud.githubusercontent.com/assets/2480569/23100555/8db13e24-f684-11e6-8d4f-3ea1aa980e56.png)

**Comment by jhia** [comment]
Hi @probonopd what's shown at the DevTools console?

**Comment by probonopd** [comment]
![screenshot from 2017-02-23 23-11-20](https://cloud.githubusercontent.com/assets/2480569/23281393/70bf4828-fa1d-11e6-8cac-7b709ed49453.png)

**Comment by jhia** [comment]
Thank you! We're so sorry, _Libris_ is currently under development and ~it has too many bugs~ we are so grateful with everyone that tell us any issue found. I'm gonna fix it on this new commit, in the meanwhile (this is not a fixing but I think it'd work) you can copy the config.json file wrapped at the repo or create a new `config.json` file in your `/home/me/` directory
```
{
  "directory": "default",
  "extensions": [ "epub" ]
}
```
I promise to give you some pretty good news as queekly as possible 💌 
Again, _thank you_ ❤️

**Comment by jhia** [comment]
Hello @probonopd I think commit c38ebb96d374380858bafb3d299b3f1409b7dfaf fixes this error.
